name: "Default Workflow"

on: push

jobs:
  hadolint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "./app"
    steps:
      - uses: actions/checkout@v3  
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  call-workflow-ci-java-gradle:
    needs:
      - hadolint
    uses: kumabes-org/reusable-workflows-ci-java-gradle/.github/workflows/ci.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"
      project-name: "java-gradle-springboot-application"
      java-distribution: "zulu"
      java-version: "11"
      gradle-version: "7.6.1"
    secrets: inherit

  call-workflow-sonarqube:
    needs:
      - call-workflow-ci-java-gradle
    uses: kumabes-org/reusable-workflows-sonarqube/.github/workflows/main.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"    
      project-name: "java-gradle-springboot-application"
    secrets: inherit

  call-workflow-codeql:
    needs:
      - call-workflow-ci-java-gradle
    uses: kumabes-org/reusable-workflows-codeql/.github/workflows/main.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"    
      project-name: "java-gradle-springboot-application"
      languages: "java"
    secrets: inherit
